include:
  - component: $CI_SERVER_FQDN/nagyv/gitlab-opencode/opencode@2
    inputs:
      config_dir: ${CI_PROJECT_DIR}/opencode-config
      auth_json: $OPENCODE_AUTH_JSON # The variable name for your OpenCode authentication JSON
      command: optional-custom-command
      message: "Your prompt here"
